Moving more docs around

diff --git a/sh/git-jump b/sh/git-jump
--- a/sh/git-jump
+++ b/sh/git-jump
@@ -76,3 +76,24 @@ type "mode_$mode" >/dev/null 2>&1 || { usage >&2; exit 1; }
 "mode_$mode" "$@" >"$tmp"
 test -s "$tmp" || exit 0
 open_editor "$tmp"
+
+gitdiffb() {
+    if [[ "$@" -ne 2 ]]; then
+        echo -e 'Usage: gitdiffb branch1 branch2'
+        exit 127
+        # if you care you can do man bash and search for exit codes to get the
+        # correct code to use here
+    fi
+
+    git log --graph \
+    --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%Creset' \
+    --abbrev-commit --date=relative $1..$2;
+
+}
+
+if [[ -n "$(command -v fzf)" ]]; then
+    gitdiffb "$@"
+else
+    gitdiffb "$@" | fzf -
+fi
+
